CREATE DATABASE Quanlyshophoa
GO

USE Quanlyshophoa
GO

CREATE TABLE SANPHAM
(
MASP INT IDENTITY ,
TENSP NVARCHAR(50) NOT NULL UNIQUE,
DGNHAP INT NOT NULL,
DGBAN INT NOT NULL,
SOLUONGTON INT NOT NULL,
PRIMARY KEY(MASP ASC)
);
GO

CREATE TABLE TAIKHOAN
(
MANV INT IDENTITY ,
HOTEN NVARCHAR(50) UNIQUE NOT NULL,
TENDN NVARCHAR(50) UNIQUE NOT NULL,
PASS NVARCHAR(100) NOT NULL,
CHUCVU NVARCHAR(50) NOT NULL,
DIACHI NVARCHAR(50) NOT NULL,
SDT NVARCHAR(20) NOT NULL,
PRIMARY KEY(MANV ASC)
);
GO

CREATE TABLE KHACH
(
MAKH INT IDENTITY,
TENKH NVARCHAR(50) NOT NULL UNIQUE,
DIACHI NVARCHAR(50) NOT NULL,
SDT NVARCHAR(20) NOT NULL,
PRIMARY KEY(MAKH ASC)
);
GO

CREATE TABLE HDBAN
(
MAHDB INT IDENTITY NOT NULL,
MAKH INT NOT NULL,
MANV INT NOT NULL,
NGLAP DATETIME DEFAULT GETDATE(),
THANHTIEN INT NOT NULL,
PRIMARY KEY(MAHDB ASC),
FOREIGN KEY(MAKH) REFERENCES KHACH(MAKH),
FOREIGN KEY(MANV) REFERENCES TAIKHOAN(MANV)
);
GO

CREATE TABLE CHITIETHDBAN
(
MAHDB INT NOT NULL,
MASP INT NOT NULL,
SOLUONG INT NOT NULL,
TONG INT NOT NULL,
PRIMARY KEY(MAHDB ASC,MASP ASC),
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
FOREIGN KEY(MAHDB) REFERENCES HDBAN(MAHDB)
)
GO

INSERT INTO SANPHAM VALUES
(N'Hoa loa kèn',5000,12000, 1000),
(N'Hoa ly',7000,10000, 1000),
(N'Hoa lan',10000,20000, 1000),
(N'Hoa cúc',15000,20000, 1000),
(N'Hoa hồng',12000,20000, 1000),
(N'Hoa đỗ quyên',14000,20000, 1000)
GO

INSERT INTO TAIKHOAN(HOTEN,TENDN,PASS,CHUCVU,DIACHI,SDT) VALUES
(N'Huỳnh Khôi',N'Hkhoi763', N'123',N'Quản lí',N'32 Sau Ga',N'0935451084'),
(N'Huỳnh Kha',N'Hkha123',N'123',N'Nhân viên', N'30 Sau Ga',N'0934411083'),
(N'Thành Đạt',N'Tdat123',N'1235',N'Thủ kho', N'22 Sau Ga',N'0934411075')
GO

ALTER TABLE TAIKHOAN
ADD CONSTRAINT C_CHUCVU CHECK(CHUCVU=N'Quản lí' or CHUCVU=N'Nhân viên' or CHUCVU=N'Thủ kho')
GO

ALTER TABLE SANPHAM
ADD CONSTRAINT C_DG CHECK(DGBAN>DGNHAP)
GO

ALTER TABLE SANPHAM
ADD CONSTRAINT C_SOLUONG CHECK(SOLUONGTON>0 OR SOLUONGTON=0)
GO

CREATE TRIGGER TRG_CTHD_SP ON CHITIETHDBAN
FOR INSERT AS 
BEGIN
	UPDATE SANPHAM
	SET SOLUONGTON=SOLUONGTON-(SELECT SOLUONG FROM inserted WHERE MASP=SANPHAM.MASP)
	FROM SANPHAM
	JOIN inserted ON SANPHAM.MASP=inserted.MASP
END
Go
